[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Removido redirecionamento de functions pois agora usamos Edge Functions (que rodam direto na rota /api/gerar)